#pragma once
#include <iostream>
#include <fstream>
#include <sys/stat.h>
#include <filesystem>
#include <regex>
#include <iostream>
#include <Windows.h>
#include <fstream>
#include <stdio.h>
#include <string.h>
#include <fstream>
#include <stdlib.h>
#include <WinUser.h>
#include <Windows.h>
#include <stdio.h>
#include <string.h>
#include <cstdio>
#include <Lmcons.h>
#include "Mal.h"
#include "jesus.h"
#include "dWeb.h"
#include <cstdio>
#include <string>
#include <time.h>
#include <ctime>
#include <cstdlib>